# globals & constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

#SHIP_TURN_AMOUNT = 3
#SHIP_THRUST_AMOUNT = 0.25
#SHIP_RADIUS = 30

INITIAL_ROCK_COUNT = 5

PATH_IMAGES = 'images/'

# DEBUG = False
DEBUG = True